version: "3.8"

services:
  database:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'netisanov'
      POSTGRES_PASSWORD: 'q34502010'
      POSTGRES_DB: 'database'
    ports:
      - 5432:5432