# Generated by Django 3.2.8 on 2021-10-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_chel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
