# Generated by Django 3.2.8 on 2021-11-02 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_chel', '0003_auto_20211102_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='_scouts_chel_person_siblings_+', to='scouts_chel.Person', verbose_name='Братья/Сестры'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
