# Generated by Django 3.2.8 on 2021-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_chel', '0004_auto_20211102_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='staff_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
    ]
