# Generated by Django 3.2.8 on 2021-11-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_chel', '0006_rename_is_staff_person_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
