# Generated by Django 3.2.8 on 2021-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_chel', '0008_auto_20211103_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Женский'), ('M', 'Мужской')], default='F', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tie',
            field=models.CharField(choices=[('NO', 'Нет галстука'), ('BL', 'Голубой'), ('GR', 'Зеленый'), ('YE', 'Желтый')], default='NO', max_length=2, verbose_name='Галстук'),
        ),
    ]
