# Generated by Django 3.2.8 on 2021-11-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_chel', '0009_auto_20211103_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='parents',
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_mother', to='scouts_chel.person'),
        ),
    ]
