# Generated by Django 3.2.8 on 2021-11-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_chel', '0011_person_father'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='children',
        ),
    ]
